### ISSUE TITLE
Live video feed is a bit laggy

### ISSUE THREAD

**Issue by abx393** [abx393/tello-drone-bindings#1]

**Comment by abhaybd** [comment]
+1

**Comment by arnavthareja** [comment]
This is probably more serious than it seems -- I was trying to fly my great-aunt to the hospital, and accidentally crashed into an electrical wire 500 feet in the air because the video feed lagged. Not a good outcome :(

This should be fixed ASAP!

**Comment by abx393** [comment]
Lots of great discussion on this issue! We'll table it for now though.

**Comment by abhaybd** [comment]
So sorry for your loss, I am saddened to hear about your great aunt.

This project uses h264 encoding though, which is ultra low-latency and low-bandwidth. So it's probably your fault that she's dead :(

**Comment by abx393** [comment]
@arnavthareja to clarify you were trying to fly your great-aunt to the hospital on a drone the size of your hand?
