### ISSUE TITLE
Gif on readme is out of sync

### ISSUE THREAD

**Issue by arnavthareja** [abx393/tello-drone-bindings#2]
Please fix this, it doesn't accurately represent the capabilities of your system! I would love to see this synced up!!!

**Comment by arnavthareja** [comment]
Agreed!

**Comment by abhaybd** [comment]
Very disappointing that the gifs are not synchronized. I was about to use this project for my multinational enterprise, but upon seeing this I have henceforth changed my mind.

If this is fixed, I will reconsider this.

**Comment by arnavthareja** [comment]
I am so sorry to hear about your situation. I hope your large multinational enterprise business was not disrupted too greatly. Warmest wishes, Arnav.

**Comment by abx393** [comment]
Looks like there's not much traction on this issue, closing for now.
